version: '3.8'

networks:
  web:
    external: true
    name: homelab-web

services:
  magicpages-frontend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: magicpages-frontend
    restart: unless-stopped
    networks:
      - web
    ports:
      - "8101:80"
    environment:
      - NODE_ENV=production
    healthcheck:
      test: ["CMD", "wget", "--quiet", "--tries=1", "--spider", "http://localhost/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
